### ISSUE TITLE
Extension eventually stops working

### ISSUE THREAD

**Issue by rfrelow** [WebMemex/webmemex-extension#121] opened 2017-07-29 08:16 UTC
I'm using Firefox, and have "store every visited webpage" checked. After some time, the extension stops making new snapshots. If I disable and re-enable the extension, it works for a few pages then stops again. If I completely remove and reinstall the extension, it works again for some time (until it breaks).

When it breaks it looks like this, and won't work even for manually capturing pages:

<img width="320" alt="screen shot 2017-07-29 at 1 10 57 am" src="https://user-images.githubusercontent.com/23464021/28743296-7dd85bc8-73fb-11e7-9df9-bc1231020e8f.png">

It feels like it's hitting a limitation of stored pages. Using version 0.2.3.

**Comment by Treora** [comment] 2017-07-29 12:02
Thanks for reporting. I would like to investigate, but I have no idea what would be the cause of this. So unless I would end up encountering the same problem myself, I would need to hear more information about the situation. If you're comfortable with browser consoles, you might be able to find relevant error messages in the developer console for the extension's background script (should be possible to open through `about:debugging`), or perhaps in the developer console of the page itself (F12).

In any case, it would be helpful to know after roughly how many pages the issue occurs. Dozens, hundreds, ...?

**Comment by rfrelow** [comment] 2017-07-29 15:42
I'll play around with it more later, but here are the errors I'm getting right now. This doesn't show up when the extension is working:

<img width="1678" alt="screen shot 2017-07-29 at 8 36 55 am" src="https://user-images.githubusercontent.com/23464021/28746058-c357a38c-7439-11e7-8ccc-1d2f51168319.png">

<img width="1679" alt="screen shot 2017-07-29 at 8 39 54 am" src="https://user-images.githubusercontent.com/23464021/28746060-c8009164-7439-11e7-937b-1aadd97e48a9.png">

Database quota exceeded it seems.

**Comment by rfrelow** [comment] 2017-07-30 14:46
This happens roughly after a few hundred pages have been saved. Let me know if there's anything else I can provide that can help!

**Comment by Treora** [comment] 2017-08-01 19:41
That indeed looks like you have hit a storage limit. I fear there is not much we can do about that in the current setup, besides telling the user what went wrong *(edit: b613ff1 adds an error message to popup)*.

We could anyhow request the `unlimitedStorage` permission in the manifest *(edit: done in d5dd52f)*, but Firefox does not currently support this (see [MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions#Browser_compatibility)).

It could be questioned whether the switch to store _every_ web page is even worth keeping. It does currently not make a great experience, since it stores pages every time they are visited or even reloaded, and it is too modal to my taste (it is invisible and thereby easy to forget about).

**Comment by Treora** [comment] 2018-08-06 16:28
Closing this issue. Automatically storing pages is no longer a feature, so presumably storage limits are not hit so easily anymore.

**Closed as completed by Treora** 2018-08-06 16:28 UTC
